repeat task.wait() until game:IsLoaded() 

if (not _G.LoadedX) then 
    _G.LoadedX = true 
    getgenv().Workspace = game:GetService("Workspace")
    getgenv().RunService = game:GetService("RunService")
    getgenv().GuiService = game:GetService("GuiService")
    getgenv().Stats = game:GetService("Stats")
    getgenv().SoundService = game:GetService("SoundService")
    getgenv().NonReplicatedCSGDictionaryService = game:GetService("NonReplicatedCSGDictionaryService")
    getgenv().CSGDictionaryService = game:GetService("CSGDictionaryService")
    getgenv().LogService = game:GetService("LogService")
    getgenv().ContentProvider = game:GetService("ContentProvider")
    getgenv().KeyframeSequenceProvider = game:GetService("KeyframeSequenceProvider")
    getgenv().AnimationClipProvider = game:GetService("AnimationClipProvider")
    getgenv().Chat = game:GetService("Chat")
    getgenv().MarketplaceService = game:GetService("MarketplaceService")
    getgenv().Players = game:GetService("Players")
    getgenv().PointsService = game:GetService("PointsService")
    getgenv().AdService = game:GetService("AdService")
    getgenv().HttpRbxApiService = game:GetService("HttpRbxApiService")
    getgenv().NotificationService = game:GetService("NotificationService")
    getgenv().ReplicatedFirst = game:GetService("ReplicatedFirst")
    getgenv().TweenService = game:GetService("TweenService")
    getgenv().MaterialService = game:GetService("MaterialService")
    getgenv().TextService = game:GetService("TextService")
    getgenv().PlayerEmulatorService = game:GetService("PlayerEmulatorService")
    getgenv().CorePackages = game:GetService("CorePackages")
    getgenv().StudioData = game:GetService("StudioData")
    getgenv().StarterPlayer = game:GetService("StarterPlayer")
    getgenv().StarterPack = game:GetService("StarterPack")
    getgenv().StarterGui = game:GetService("StarterGui")
    getgenv().CoreGui = game:GetService("CoreGui")
    getgenv().LocalizationService = game:GetService("LocalizationService")
    getgenv().CloudLocalizationTable = game:GetService("CloudLocalizationTable")
    getgenv().PolicyService = game:GetService("PolicyService")
    getgenv().TeleportService = game:GetService("TeleportService")
    getgenv().JointsService = game:GetService("JointsService")
    getgenv().CollectionService = game:GetService("CollectionService")
    getgenv().PhysicsService = game:GetService("PhysicsService")
    getgenv().BadgeService = game:GetService("BadgeService")
    getgenv().Geometry = game:GetService("Geometry")
    getgenv().FriendService = game:GetService("FriendService")
    getgenv().InsertService = game:GetService("InsertService")
    getgenv().GamePassService = game:GetService("GamePassService")
    getgenv().Debris = game:GetService("Debris")
    getgenv().TimerService = game:GetService("TimerService")
    getgenv().CookiesService = game:GetService("CookiesService")
    getgenv().UserInputService = game:GetService("UserInputService")
    getgenv().KeyboardService = game:GetService("KeyboardService")
    getgenv().MouseService = game:GetService("MouseService")
    getgenv().VRService = game:GetService("VRService")
    getgenv().ContextActionService = game:GetService("ContextActionService")
    getgenv().ScriptService = game:GetService("ScriptService")
    getgenv().AssetService = game:GetService("AssetService")
    getgenv().TouchInputService = game:GetService("TouchInputService")
    getgenv().BrowserService = game:GetService("BrowserService")
    getgenv().AppStorageService = game:GetService("AppStorageService")
    getgenv().AnalyticsService = game:GetService("AnalyticsService")
    getgenv().ScriptContext = game:GetService("ScriptContext")
    getgenv().RbxAnalyticsService = game:GetService("RbxAnalyticsService")
    getgenv().HttpService = game:GetService("HttpService")
    getgenv().Lighting = game:GetService("Lighting")
    getgenv().Selection = game:GetService("Selection")
    getgenv().RuntimeScriptService = game:GetService("RuntimeScriptService")
    getgenv().RobloxReplicatedStorage = game:GetService("RobloxReplicatedStorage")
    getgenv().IXPService = game:GetService("IXPService")
    getgenv().GamepadService = game:GetService("GamepadService")
    getgenv().MeshContentProvider = game:GetService("MeshContentProvider")
    getgenv().SolidModelContentProvider = game:GetService("SolidModelContentProvider")
    getgenv().HSRDataContentProvider = game:GetService("HSRDataContentProvider")
    getgenv().LodDataService = game:GetService("LodDataService")
    getgenv().TextBoxService = game:GetService("TextBoxService")
    getgenv().ControllerService = game:GetService("ControllerService")
    getgenv().HapticService = game:GetService("HapticService")
    getgenv().MemStorageService = game:GetService("MemStorageService")
    getgenv().MessageBusService = game:GetService("MessageBusService")
    getgenv().NetworkClient = game:GetService("NetworkClient")
    getgenv().ChangeHistoryService = game:GetService("ChangeHistoryService")
    getgenv().Visit = game:GetService("Visit")
    getgenv().GuidRegistryService = game:GetService("GuidRegistryService")
    getgenv().PermissionsService = game:GetService("PermissionsService")
    getgenv().Teams = game:GetService("Teams")
    getgenv().ReplicatedStorage = game:GetService("ReplicatedStorage")
    getgenv().TestService = game:GetService("TestService")
    getgenv().SocialService = game:GetService("SocialService")
    getgenv().TextChatService = game:GetService("TextChatService")
    getgenv().ProximityPromptService = game:GetService("ProximityPromptService")
    getgenv().VoiceChatService = game:GetService("VoiceChatService")
    getgenv().GroupService = game:GetService("GroupService")
    getgenv().FaceAnimatorService = game:GetService("FaceAnimatorService")
    getgenv().AvatarEditorService = game:GetService("AvatarEditorService")
    getgenv().ScriptRegistrationService = game:GetService("ScriptRegistrationService")
    getgenv().VideoCaptureService = game:GetService("VideoCaptureService")
    getgenv().SpawnerService = game:GetService("SpawnerService")
    getgenv().PathfindingService = game:GetService("PathfindingService")
    getgenv().Heartbeat = RunService.Heartbeat 
    getgenv().RenderStepped = RunService.RenderStepped 
    getgenv().Stepped = RunService.Stepped 
    getgenv().Player = Players.LocalPlayer 
    getgenv().Character = Player.Character or Player.CharacterAdded:Wait() 
    getgenv().HumanoidRootPart = Character:WaitForChild("HumanoidRootPart")
    getgenv().Humanoid = Character:WaitForChild("Humanoid") 
    getgenv().Camera = Workspace.CurrentCamera
    getgenv().Huge = math.huge 

    Workspace:GetPropertyChangedSignal("CurrentCamera"):Connect(function()
        getgenv().Camera = Workspace.CurrentCamera 
    end)

    Player.CharacterAdded:Connect(function(character)
        getgenv().Character = character 
        getgenv().HumanoidRootPart = Character:WaitForChild("HumanoidRootPart")
        getgenv().Humanoid = Character:WaitForChild("Humanoid")
    end)

    for index, value in pairs(getconnections(Player.Idled)) do 
        value:Disable()
    end 
end 
